### ISSUE TITLE
File upload not working in IE

### ISSUE THREAD

**Issue by Gemorroj** [jquery-form/form#159]
This example http://jquery.malsup.com/form/#file-upload
If you select a return type of JSON, that example does not work in IE8 in version jquery.form 2.94

**Comment by Voxen** [comment]
I also have this problem with IE8 and version 2.94.
Forms having file upload inputs are submitted as GET instead of POST.
Happens only with IE, not with Firefox or Safari.

Example:

HTML:
&lt;form enctype="multipart/form-data"&gt;
&lt;input type="file" id="file" name="file"&gt;
&lt;/form&gt;

JS:
$('form').ajaxSubmit(
{
    url: 'upload.php',
    type: 'POST',
    timeout: 300000
});

This is submitted with GET instead of POST!

I found a workaround to make it work, forcing method POST before submit:

$('form').prop('method', 'POST').ajaxSubmit(....

Hope it helps!

**Comment by Gemorroj** [comment]
&lt;form enctype="multipart/form-data"&gt;
default method is GET.

**Comment by shazahm1** [comment]
@Voxen 

Thanks for this tip. I can't believe that little tid bit is not in tutorials, SO or documentation. This was the only way I could get upload to work in all browsers. OR maybe i missed everywhere where method was set in the form tag. OR maybe I should have taken a break and come back with fresh eyes.
