### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by issackelly** [jquery-form/form#22]
Using JQuery 1.4.1 and trunk on jquery.form I get this error in Google Chrome (latest)

Uncaught TypeError: object is not a function, and it says line 2, it's presumably on the iFrame.

```
<form id="srv_upload_image" method="post" enctype="multipart/form-data" action="">
    <input type="files" />
    <input type="submit" class="srv_button insert" id="srv_upload_image_action" value="Upload">
</form>
</div>
<script type="text/javascript">
$(document).ready(function(){
    $("form#srv_upload_image").ajaxForm({
            dataType: 'json',
            iframe: true,
            success : function(data,text,xhr,another){
                if(data.errors.length == 0){
                    $("#srv_image_filePane").append(data.item);
                }
                else {
                    else for (error in data.errors) alert(error);
                }
            }   
    });
```

**Comment by mitchlloyd** [comment]
I'm also struggling with this error.  The error only seems to occur when there is a file input in the form.

**Comment by jlsandell** [comment]
I've run into this as well. Again, it only occurs during a file upload (due to the iframe I'm guessing).

**Comment by galdosd** [comment]
I am having the exact same problem. I tried debugging it and I believe the problem is on line 264 of jquery.form.js:

```
$io.appendTo('body');
$io.data('form-plugin-onload', cb);
```

It seems that if the load event triggers sufficiently quickly, the 'form-plugin-onload' data on the element will not yet be set, so an attempt is made to call something that is not a function. As a result the callback is not called at all.

I simply swapped the two lines and that fixed the issue completely for my purposes. I also doubt that that could cause any other bugs, however, I didn't have time to test it more thoroughly, and it's possible I'm misunderstanding something about the jquery forms plugin or jquery, so someone should at least run the test suite through it before committing. In the meantime, to the two of you who were having the same problem, you can just swap those two lines in the jquery form code:

```
$io.data('form-plugin-onload', cb);
$io.appendTo('body');
```

and hopefully you'll be lucky too. Best wishes!

Patch follows:

```
262a263,265
>                               // save the callback so the iframe can get it
>                               // we need to do this *first* (see github issue #22)
>                               $io.data('form-plugin-onload', cb);
265d267
<                               $io.data('form-plugin-onload', cb);`
```

**Comment by shad42** [comment]
I can confirm the bug.

@galdosd: Unfortunately, your workaround does not fix the bug at all. :(

**Comment by mishermasher** [comment]
I found that if the server-side script returns some text in the response then this error doesn't occur.  I didn't look closely at the source to see why this is true, but I thought I'd share.

**Comment by malsup** [comment]
Can someone post a simple test page that shows the problem?  Thanks.
