### ISSUE TITLE
Aborting ajax requests

### ISSUE THREAD

**Issue by iammartinbelobrad** [jquery-form/form#221]
Please add ajaxAbort() method or return in your methods ajaxSubmit and ajaxForm XHR object, please. The library does not abort the request.

**Comment by StephenChan** [comment]
ajaxSubmit() and ajaxForm() don't return the XHR object, but the XHR object is passed as the first parameter to the beforeSend callback.  So you can get the XHR object by specifying a beforeSend callback, and saving that XHR object to a variable in that callback.  Then when you want to abort the upload, you can call abort() on that XHR object.

beforeSend is not an option listed in the [jQuery Form options list](http://jquery.malsup.com/form/#options-object), but it is an option to [$.ajax()](http://api.jquery.com/jQuery.ajax/), and ajaxSubmit()/ajaxForm() take any option that $.ajax() does.

So there is a way to abort the upload, though I think it would be nice if it were better documented than it is now - or if there were a convenient utility function to abort, as you suggested.  I was stuck on this for a little while myself, because I initially expected ajaxSubmit()/ajaxForm() to return the XHR object, and I was mainly only looking at the jQuery Form options list instead of the $.ajax() options list.  I only found the answer from [this issue](https://github.com/malsup/form/issues/212).

**Comment by iammartinbelobrad** [comment]
I do not know, it seems to us more appropriate and logical way return XHR object, like it has with jQuery $.ajax

**Comment by andrewharry** [comment]
I would prefer the xhr object returned.  Especially seeing as this plug-in is unlikely to be used with chaining.

**Comment by malsup** [comment]
The jqHXR is now stored on the form object and is accessible using the `data` method.  

```
var form = $('#myForm').ajaxSubmit({ ... });
var xhr = form.data('jqxhr');
...
```
