### ISSUE TITLE
IE9 - SCRIPT5: Access is denied

### ISSUE THREAD

**Issue by mickeyze** [jquery-form/form#286]
IE9 Reports following error :

SCRIPT5: Access is denied.
jquery.form.js?1360575784, line 483 character 17

![ie_error](https://f.cloud.github.com/assets/2063771/144660/f0b7efca-7430-11e2-865e-8fd26cbc7d2a.jpg)

**Comment by hemerfc** [comment]
Hi.

I had the same issue.

I replaced 'about:blank' by window.location.href in the line below, and this worked.

92  iframeSrc: /^https/i.test(window.location.href || '') ? 'javascript:false' : 'about:blank'

**Comment by mickeyze** [comment]
I understand that main idea in that line was to find is there is a usage of https, but after changing that line of code to 
iframeSrc: /^https/i.test(window.location.href || '') ? 'javascript:false' : window.location.href 

i don't work as all. Well function tries to execute it self, and after that it is stopped and back to beginning.

**Comment by schplay** [comment]
I'm having this exact same problem. It works fine in Chrome but for some reason won't work in IE 8 or 9. I'm using jQuery 1.9.1 and have tried 1.9.0 and 1.8.3.

I've attempted to read and apply the fix hemerfc suggested but it only added a new error to the mix. This problem only occurs when trying to actually upload the file.

**Comment by tburd** [comment]
I was discussing this problem here: https://github.com/malsup/form/issues/289
I have also tried to do what @hemerfc said, but the same error persists...

@schplay, @mickeyze do you have issues with the demo page? 
http://jquery.malsup.com/form/#file-upload

Anybody else? Any idea?

**Comment by schplay** [comment]
The demo page seems to work fine without the error. I've looked at the source for it and can't find any appreciable differences between it and my own code.

**Comment by malsup** [comment]
I'd recommend creating a very simple test page and then adding to it until it is like the one you have that is failing.  At some point it should become clear what is causing the issue (hopefully).  

One thing to watch out for that will cause an access denied error in IE is triggering a form submit in response to a file input change event.  That is not allowed.

**Comment by mickeyze** [comment]
@malsup I downloaded your code from from page http://jquery.malsup.com/form/progress3.html and tested on local server but now I don't receive any error, to be precise I don't receive anything. Form is not executed at all in IE, but in other browsers it works fine. 

Let me summarize this story : 
In IE you use iFrame for submiting page, and throw my analysis of jquery.form.js code I saw that we are receiving this error when form is tried to be submit --> Line : 483 : submitFn.apply(form);
If I write here console.log(form), I will see code of my form. Question is how do you then submit form if You already wrote "One thing to watch out for that will cause an access denied error in IE is triggering a form submit in response to a file input change event. That is not allowed."? What is purpose of this lines, if not to submit form?

Also, I replaced jquery.form.js file that I previously download from github page with jquery.form.js file from your example page (I found link from source) and now I'm receiving this error : 
jquery.form.js?1360575784, line 483 character 23

Since form is same, nothing is not changed on my page except jquery.form.js I can't understand why the error is moved to character 23, not character 17 like written previously. Any idea?

My code for form  : 

![IE9 SCRIPT5 Access is denied Issue 286 malsup form](https://f.cloud.github.com/assets/2063771/227533/e67abeea-8662-11e2-9f85-ec41698f5e49.png)

**Comment by mononcle** [comment]
same issue here. 
version: 3.28.0-2013.02.06   

No updates on this?

**Comment by tburd** [comment]
I moved to another script... works greate on IE (all versions).
https://github.com/valums/ajax-upload

**Comment by malsup** [comment]
@mononcle do you have a link that shows the problem?

**Comment by mickeyze** [comment]
Well, I moved to https://github.com/blueimp/jQuery-File-Upload
And after installing that plugin I saw same error, and after investigation I figured out that versions of jQuery plugins and jQuery core file are not compatible. I managed to fix it using jQuery migrate plugin (code.jquery.com/jquery-migrate-1.1.1.js) and I solved it correctly.

**Comment by thoresuenert** [comment]
@mickeyze  how to fix that issue? Its very important for me, but i couldnt find any solution

**Comment by mickeyze** [comment]
I understand you, I was at same situation. 
You can try to exclude all .js files that you are loading on page or layout and try to include them sequentially until you see which .js file causes collision.
Try to user .jquery migrate file (code.jquery.com/jquery-migrate-1.1.1.js) and try to use versions of jQuery plugin files that are used on demo site. 
If that don't work than try other jquery upload scripts like : https://github.com/blueimp/jQuery-File-Upload
Good luck!

**Comment by thoresuenert** [comment]
I am one step further. My problem is: jquery click on input and append Input files dynamically. jquery form plugin works well.

**Comment by mickeyze** [comment]
You think like that you have nested forms that are created dynamically ?
With  https://github.com/blueimp/jQuery-File-Upload you don't need to use forms at all

**Comment by jes-carr** [comment]
I had the same issue. My app is using Backbone, and I think is something related to generating the form dynamically. Unfortunately I didn't have time to dive much more into the exact issue, and I moved to https://github.com/blueimp/jQuery-File-Upload

**Comment by thoresuenert** [comment]
SCRIPT5: Access is denied.
is an Security Feature of IE. 
You arent allowed to manipulate a Form in anyways.
No JQuery simulated Submit via <a> tag
No dynamically added Form fields

I tried to add via <a> tags new File input fields to handle Layouts. 
That result in Access is denied.

After that reserach i added 20 File Input fields on serverside.
Than the Plugin can inject the Submit Event and clone the "untouched" form and everything is fine.

**Comment by ghost** [comment]
I get this error when I hide the '<input type="file...' element (because they are hideous and you can't style them) and call it's click event via js. If I show the input element, and the user clicks on that, then the error does not occur.

**Comment by ghost** [comment]
I've found a workaround. Instead of using a div or a button, and attaching a handler to call the click handler on the input element, simply use a label.

<label for="inputFile">Click here to upload</label>
<input type="file" id="inputFile" style="display:none"/>

Click on the label and the upload will work.. well it works for me in IEs 8&9 anyway.

**Comment by radiocity** [comment]
I had the same security issue. The code check for ie version and manipulate by plugin options:

``` JavaScript
$('#image_upload').on('change',function(e){
        $(this).closest('form').ajaxSubmit({
            url: 'http://example.com/ajax-upload',
            iframe: (window.requestAnimationFrame)?false:true, // > ie9
            iframeSrc: 'javascript:false',
            complete: function(data) {
                console.log(data.responseText);
            }
        });
    });

```

Quite simple, isnt it? ;)

**Comment by MartijnHols** [comment]
I had the same problem with IE 9 when a user was sent a link in the mail with which he could upload a file. Since GMail always uses a gateway script before forwarding the user to the page, it causes IE 9 to regard the entire tab as owned by that domain from Google for the remainder of its existence (at least, that's my theory). This prevented calling post() on the submit button in the iframe since it thinks it's cross-domain (which obviously isn't allowed).
Opening a new tab and copy-pasting the URL into it did not experience this issue. This made it hard to debug the issue for a long time.

I tried forwarding the user to the current page (header, javascript and meta), but this didn't seem to rid the tab of the wrong domain-state. I eventually solved it by just putting the entire frame in a frameset:

```
//if *'noreferer' is unset* then: send a HTML page with the following body:
<frameset rows="100%" cols="100%">
  <frame src="<?php echo htmlspecialchars($_SERVER['REQUEST_URI']) . '?noreferer=1'; ?>">
</frameset>
//end;
```

**Comment by CheapSk8** [comment]
I am reviving this thread for others who have encountered this, since I know it's still floating around. The current version of the script has the "about:blank" workaround added in it, but the issue still occurs in IE9. From what I found with regards to the error in IE9, it appears to be a timing issue. With a little testing I was able to determine that the error occurred because the "form.submit" call was made before the iFrame had loaded in the page (approx 55-60ms from what I found). Additionally, in the application I am using it with, the submit happens on a button click event, and I found that though the first click resulted in the error, a second button click submitted fine.

This might not be the case with everyone reporting this issue, but I tested a polling solution to challenge this hypothesis and I was able to eliminate the issue completely. I replaced the original try...catch statement containing the form.submit() around line 588 with the below code and it resolve the issue for me. 

_Edited to add the following:_
Clear out the finally as well because it will continue execution while the timeout is going. The finally should occur with the timeout function.

_Edited to add the following:_
Disregard my comment about it solving it. This does solve the load issue, but the rest of the script executes in the thread causing other issues. Damn you IE9.

Replace:

```
try {
    form.submit();
} catch (err) {
    // just in case form has element with name/id of 'submit'
    var submitFn = document.createElement('form').submit;
    submitFn.apply(form);
}
```

With:

```
var tryCount = 0;
var maxTry = 10;
var maxTime = 50;
function trySubmit() {
    tryCount = tryCount + 1;
    try {
        form.submit();
        tryCount = maxTry;
    }
    catch (err) {
        if (tryCount < maxTry) {    // only attempt 10 times (10*50ms = 500ms/.5s)
            setTimeout(trySubmit, maxTime);
        }
        else {  // hit this in the end and move on
            // just in case form has element with name/id of 'submit'
            var submitFn = document.createElement('form').submit;
            submitFn.apply(form);
        }
    }
    finally {
        if (tryCount >= maxTry) {
            // reset attrs and remove "extra" input elements
            form.setAttribute('action', a);
            form.setAttribute('enctype', et); // #380
            if (t) {
                form.setAttribute('target', t);
            } else {
                $form.removeAttr('target');
            }
            $(extraInputs).remove();
        }
    }
}
setTimeout(trySubmit, maxTime);
```

**Comment by wong2** [comment]
check @Russell-Horwood 's solution

**Comment by dep-darkLonely** [comment]
Today,I meet the same security problem with IE9.As far as I am concerned，I recommend @Russell-Horwood‘s solution，because IE9 upload file can only by click the element of type=file brower button。
Use label(eg：div、button、label) element cover type=file element, click label element on the surface，actually click the element of type = file brower button。
example：
![image](https://user-images.githubusercontent.com/30953224/46939635-63ef4900-d099-11e8-9ec8-afcf74673ca1.png)
There are 2 button the same position are the element of type=file brower button and choice file button；
