### ISSUE TITLE
jQuery Form Plugin, really doesn't work in IE

### ISSUE THREAD

**Issue by ericwang14** [jquery-form/form#302]
I really don't know how can let this Plugin works in IE, If the server response 202, and the response content-type: application/json, the IE tries to download the response.

If server response 505, the response body are gone, I can get nothing in the error handle function.

I really don't know how to use it!! IT IS IE PROBLEM OR PLUGIN DEFECT?

**Comment by malsup** [comment]
Is this a form with a file upload?

**Comment by ericwang14** [comment]
yes, a form with file upload

**Comment by malsup** [comment]
Then it helps to understand exactly what the plugin is doing.  Since IE < 10 does not support ajax file uploads, the plugin simulates the user experience by submitting the original form with the response targeted to a dynamically created iframe.  When the iframe loads the server response, the plugin extracts the response and invokes callback handlers.

In the case where the server responds with a header content-type set to "application/json" that trigger's IE's default download behavior.  To avoid this, do not set the content-type header to "application/json".  Leave it as text/html or text/plain.

In the case where the server has an actual error it will return an error response page with appropriate status codes set in the response header.  This presents two problems for the plugin:  

1) it cannot access the response headers 
2) it cannot determine from the response body whether or not the request was successful

A potential solution, if you have control over the error response page, is to add attributes on the body element that the plugin will look for.  The plugin will attempt to access "status" and "statusText" attributes on the response's body element.  So if your error page includes something like `<body status="500">` then your error handler will be triggered.

Hope this helps.

**Comment by ericwang14** [comment]
Thanks for you explain malsup.
Actually I did like your suggestion.
1. use text/html or text/plain instead of 'application/json'.
2. fully control for the error response, I add error message in the successful response body, and then extract and handle it.

Its just need do little hack for the IE, just not happy with this.

**Comment by scottord** [comment]
Thank you, malsup, for the detailed explanation - I was able to change the response header of the web service that was not working in IE<=9 and everything's working now!

**Comment by ishanjain123** [comment]
Hello Malsup,

Actually I have a problem in upload the file in IE -7,8,9. Can you please let me know how to fix it ? It works fine in other browsers.

Thanks

**Comment by ericwang14** [comment]
Hi ishanjain123,

Which kind of problem you're facing now? Can you give us some more details?

**Comment by janwidmer** [comment]
Hey Malsup,
I am also trying to work around the IE9 Limitation with an ajax file upload and as soon as I set the content-type to text/html or text/plain, I get a 406 Not Acceptable Error back when I try to upload a file. Any suggestion?

Could you explain what adding a textarea to the response should help?
(Mentioned here: http://malsup.com/jquery/form/#file-upload)

Thanks for any inputs
Jan

**Comment by rekhabadri** [comment]
Hi,

Can anyone help to understand, why IE is unable to process the Request Header parameters?

From Mentioned url: http://malsup.com/jquery/form/#file-upload, when I tried to set Request Header parameter as below

(function() {  
        $('form').ajaxForm({
            beforeSend: function(e) {  
                e.setRequestHeader('token', 'euejrhzkehrkherkhekr');
            },  
            dataType : 'json',
            success: function() {
                alert("file uploaded successfully");
            }
        }); 
    })(); 

IE unable to get the request header token. whereas other browsers like chrome and firefox are able accept the headers. 

Thanks.

**Comment by ktriek** [comment]
Hi Malsup,

In the case where the server responds with a header content-type set to "application/json" that trigger's IE's default download behavior. "application/json"

Is there any solution to avoid this other than changing the the response header?

**Comment by vibs2003** [comment]
Hello @malsup,

 i am not able to post files using jquery form plugin in IE 9. could you please help me?

Actually it is hitting the action method with files but not able to return response from server. it gives an error "Server cannot append header after HTTP headers have been sent."

**Comment by vibs2003** [comment]
@malsup
