### ISSUE TITLE
success not firing on iframe file download

### ISSUE THREAD

**Issue by vicary** [jquery-form/form#316]
When the submit target initiates a file download with header `Content-Disposition: attachement`, success handler is not firing at all.

``` JavaScript
$('.loader').show();

$(form).ajaxSubmit({
  iframe: true
, target: '#someDiv' // setting this doesn't work
, iframeTarget: '#someIFrame' // this neither
, success: function() {
    $('.loader').hide();
  }
});
```

Is this intended and there is currently no way to detect it with javascript?

**EDIT**
I also tried `target="_blank"` in my HTML form, with AND without `iframe` option set.

``` HTML
<form class="hidden" action="/exports/csv" method="post" target="_blank"></form>
```

**Comment by skotchio** [comment]
For me success handler is firing but download popup is not showing.

**Comment by vicary** [comment]
I didn't do "popup", the file download is working fine with the `iframe` option (at least in Google Chrome). But with both `<form target="_blank">` or `iframe: true` I can not get the success callback (nor complete callback) firing.

**Comment by vicary** [comment]
I have put up a [jsFiddle](http://jsfiddle.net/vicary/ecnAD) to better describe the issue.

**Comment by malsup** [comment]
The form plugin doesn't handle this download case.  You might try this plugin:

http://johnculviner.com/post/2012/03/22/Ajax-like-feature-rich-file-downloads-with-jQuery-File-Download.aspx

**Comment by vicary** [comment]
Thanks for the suggestion.

But wow, the cookie thing is dirty, hope those browsers have a plan on improving this...

**Comment by phazei** [comment]
Actually, it does seem to work on most browsers except for Chrome, and possibly Safari.

The problem is Chrome doesn't submit a "load" event for a file download.  Works fine in FF and IE.

Was pretty simple to extend form to handle the case.  

Added:

```
        function checkDownload() {
            downloadGood = true;
            if (!callbackProcessed) {
                cb();
            }
        }
```

right after the "function checkState() {}" function
and 

```
            if (s.download) {
                setTimeout(checkDownload, 3000);
            }
```

after the

```
         setTimeout(checkState,15);
```

line.

Then just needed to get around the timeout check by changing:

```
         if (!timedOut)
```

to

```
         if (!timedOut && !downloadGood)
```

Oh, and added downloadGood to the variable definitions at the top of the fileUploadIframe function.

This presumes that some response, whatever it may be, would have been received within 3 seconds.  The timeout period can be adjusted or added as a setting, or the timeout setting could be used.  That cookie check thing could be added there if wanted too.

I had to adapt it since there's auto form integration using jquery validation and form plugins on every form on the site.
