### ISSUE TITLE
IE9 Access Denied when "form.submit();" on line 542

### ISSUE THREAD

**Issue by sunshineo** [jquery-form/form#328]
Hi,

There are several other IE9 Access Denied issues, but they are at a different location.

Please have a look.

--Gordon

**Comment by Macs75** [comment]
I had just the same problem with IE9 and the issue seems that I was invoking the browse dialog of the input field by an event click() on an other element. 
If the file field dialog is invoked clicking on the native browse button I do not have the "Access Denied" on the form submit. It seems is a security issue.
