### ISSUE TITLE
Codebase is too messy to contribute to safely

### ISSUE THREAD

**Issue by AndrewRayCode** [jquery-form/form#388]
This is a suggestive ticket to fix the state of the code in this plugin. As it stands, there are no tests and no coding standards, which is troublesome with such a popular plugin.

This ticket can be closed when:
1. A .jshintrc is introduced in the root of this project (or jslint, but jslint has fallen out of favor)
2. All one line if statements and functions are given curly braces `{` `}`.
3. The code is a boggling mess of nested functions. All functions should be declared in a top level scope unless specifically benefitting from closures. This will likely require a major refactor to make the code organized. For example, `deepSerialize` reads `options.traditional`, which would be much better passed in as a function argument. As for the rest of closing around options...well...this is not laid out well. Again, a major refactor is likely required.
4. All jshint reported errors are fixed. For example, [this line](https://github.com/malsup/form/blob/master/jquery.form.js#L1107) should be written with .value instead of ['value']. jshint also gets very angry at the nested functions. See item 3.
5. I personally consider it bad practice to include debugging logging functions in a plugin (with or without an enabling flag). I would suggest removing them, but not required for this ticket.

At the very least, code should be verifiable by jshint, which is often a very good line of defense against bugs and issues. Since this code has no tests, such verification is absolutely required. Otherwise no pull requests can have any certainty of being safe.

**Comment by malsup** [comment]
Thanks for the suggestions, Andrew.

Since this plugin has been in maintenance mode for years, I'm not planning a major rewrite.  Instead, I plan to write a new form plugin, form2, which targets modern browsers and offers IE < 10 support as an optional add on.

I won't dispute that there is plenty of room for cleanup in the code structure.  For the record, I use jshint in all my projects - opensource, private, and corporate.  Since three of your five points are jshint related I will commit my gruntfile so that you (and others) can use it if you wish (and I'll disable the `sub` option and enable the `curly` option).

**Comment by malsup** [comment]
Latest commit addresses at least some of your concerns.

https://github.com/malsup/form/commit/6c72f5cc4b36a85498dd48709dfaf1d01c416f1d

**Comment by kevindb** [comment]
Partially resolved by 8de36ff

I have limited experience with getting a project started with unit tests (when none already exist).
@AndrewRayCode would you please submit a pull request to get us started testing?
