### ISSUE TITLE
IE8 tries to download a file on ajaxSubmit.

### ISSUE THREAD

**Issue by rnikander** [jquery-form/form#396]
In IE8, when I try to submit the from with `ajaxSubmit`, IE gives a message: "To help protect your security, Internet Explorer blocked this site from downloading files to your computer. Click here for options... ".  I experimented with setting `dataType` to null or 'xml' instead of 'json', but it made no difference.

**Comment by rnikander** [comment]
I think I've got it working by changing the content type returned by the server.  It was "application/json", now it's "text/html".  If I say `dataType: 'json'` it parses it as json anyway and my app works.  I'll leave it up to you if you want to close this.

**Comment by rwky** [comment]
This is documented here http://jquery.malsup.com/form/#file-upload 
'It is important to note that even when the dataType option is set to 'script', and the server is actually responding with some javascript to a multipart form submission, the response's Content-Type header should be forced to text/html, otherwise Internet Explorer will prompt the user to download a "file". '

Basically old versions of IE don't like anything except text/html
