### ISSUE TITLE
support "text" dataType like jQuery

### ISSUE THREAD

**Issue by jackdouglas** [jquery-form/form#41]
currently returns the response data wrapped in html tags if dataType="text"
jquery supports this type - see 'dataType' under http://api.jquery.com/jQuery.ajax/

patch:

line 359:
var scr = /(json|script)/.test(s.dataType);
to
var scr = /(json|script|text)/.test(s.dataType);

**Comment by wkrsz** [comment]
And "html" (with evaling scripts)?

I wanted this plugin as an almost-drop-in replacement for Rails remote_form_for helper. Currently it loads remote html and evals some scripts inside. Right now to emulate this I have to set below option:

```
success: function() {  jQuery('#customer-dialog-inner').evalScripts(); }
```

[EDIT] ok on a second thought I decided to remove need for evaling scripts in the app anyway because it's ugly, so perhaps the plugin shouldn't encourage it either.

**Comment by malsup** [comment]
test for text datatype added.
