### ISSUE TITLE
this.form.submit() not submitted via ajaxForm

### ISSUE THREAD

**Issue by hurelhuyag** [jquery-form/form#425]
```
<div id='formTarget'>
  <form id="form" action="/image" method="post" enctype="multipart/form-data">
    <input type="file" name="image" onchange="this.form.submit()">
  </form>
<div>
<script>
  $('#form').ajaxForm({
    target : '#formTarget'
  });
</script>
```

**Comment by pokej6** [comment]
This is happening because the form plugin binds to 'submit.form-plugin' (Line 871). You are explicitly calling submit() which does not include the event namespace. Instead of having the onchange in your html, try adding this javascript:
`$('#form').on('change', function() {$(this).trigger('submit.form-plugin')});`

Note: Instead of going through the above snippet, it would probably be best to use the plugin's ajaxSubmit() as it will be more maintainable.
`$('#form').on('change', function() { $(this).ajaxSubmit({ target : '#formTarget' }) });`
You would also remove your ajaxForm() call in this case.

PS, you aren't closing your div ;)

**Comment by hurelhuyag** [comment]
Why can not use onsubmit event?

**Comment by pokej6** [comment]
Did my proposed change work for submitting the form and you're now asking a new question or am I misunderstanding?

**Comment by Rud5G** [comment]
@pokej6 thanks for also answering my question.
