### ISSUE TITLE
Sending empty file and Zend_Transfer_Adapter

### ISSUE THREAD

**Issue by Rumzik** [jquery-form/form#449]
Why is sending empty file input to server, you send in $_POST empty fileName key.

Show please, how sending http headers with empty file without ajax form. 

------WebKitFormBoundaryM1m9Pv7ycaAcmY2m
Content-Disposition: form-data; name="photo"; filename=""
Content-Type: application/octet-stream

You sending

------WebKitFormBoundaryPpk5ZobqTd1uLtCc
Content-Disposition: form-data; name="photo"

I found solution. Please change this code

<code>
1008: a.push({ name: n, value: '', type: el.type });
</code>

And write next

<code>
var emptyFile = new File([""],"",{type:"application/octet-stream"});
a.push({ name: n, value: emptyFile, type: el.type });
</code>

Thank you. Sorry my bad english ;)

**Comment by rocksit** [comment]
Hello All.

I have same problems, namely in conjunction with appache php/zend ZF1. 
It seems to me that Zend FW1 could not handle the AJAX type of POST request,
std XHR is using to propagate an empty input[type=file] field, when unsing 
POST with multipart/data format.

While common browsers post empty files like this

------WebKitFormBoundaryM1m9Pv7ycaAcmY2m
Content-Disposition: form-data; name="photo"; filename=""
Content-Type: application/octet-stream

XHR with jquery.form plugin  is doing something like this

------XHRJqueryFormBoundaryxyz
Content-Disposition: form-data; name="photo"; 

Difference is missing (empty) filename and content-type.
This leads PHP (OR Zend, depending on where $_Files 
stucture in php is rooted, I don't know. Maybe ZF2 found a solution
to this ?) to think "photo" is an empty but normal Post variable, storing it 
in $_POST and not in $_FILES.

ZF1 validator is messing up with that and throws missleading wrong size error 
due to a inappropriate error recognition in Zend_File_Transfer_Adapter_Http
As OndraM pointed out, in another related post 
https://github.com/malsup/form/commit/588306aedba1de01388032d5f42a60159eea9228#commitcomment-2180219
this is a known problem in ZF1 and here is its issue.

http://www.framework.zend.com/issues/browse/ZF-10279

but sadly, the proposed ZF1 fix http://www.framework.zend.com/issues/browse/ZF-10279
won't do the job, because it only eliminates one validator error cause (namely empty $_FILES
array) but not all the others ZF1 validator errors, that occur, when this first validation of empty
$_FILES would pass. Due to the fact, that ZF1 is not developed further but widely spread in
use, I suggest following solution to this problem.

The first part is to integrate proposed fix from  Rumzik.

change line 1008 to 

```
var emptyFile = new File([""],"",{type:"application/octet-stream"}); 
a.push({ name: n, value: emptyFile, type: el.type });
```

would force browsers to send something like this as empty file 

------WebKitFormBoundaryM1m9Pv7ycaAcmY2m
Content-Disposition: form-data; name="photo"; filename="blob"
Content-Type: application/octet-stream

This would make php recognize photo as a file in FILES array.
Sadly  I couldnt find a way to set filename="" empty, which would
be required to let php recognize an _empty_ file field.

So, if there are installed some other validators for file in ZF
like type, etc, we will get an error again, due to the fact that
php /ZF tinks, it deals with a true file.

To come arround this, we have to tell ZF that we are dealing
with a non existent file befor validation occurs.

I accomplish this in an early place of my code by doing

```
      if('POST' == $_SERVER['REQUEST_METHOD'])
         foreach($_FILES as $idx=>$file)
            if($file['size'] == 0)
               $_FILES[$idx]=array('name'=>'','type'=>'','tmp_name'=>'','error'=>4,'size' => 0 );
```

S, if I found a file with empty length, I set it to a ZF1 config of a
non existent file, so everything in validation will go fine. This workaround
means, you can not upload empty files anymore, what is no problem in my case.

Since ZF1 wont get more updates and changing ZF is a bigger and invasive task in this
hassle, this was the best way for me to go without loosing browser clint supprt and 
comfort. If you find a way for you to fix $_FILES array manually from your internal
form data information, you could omit patching jquery.form but it makes life 
easier and seems save to me. (Finally xhr call will look much more as
a native POST call for php and is more easy to handle.)

js File structure is supported in a similar way than XHR2 feature is
http://caniuse.com/#feat=xhr2
https://developer.mozilla.org/de/docs/Web/API/File
So we should not get in trouble with older clients, creating a File object in a
 jquery.form xhr2 call, compatibility is nearly same and jquery.form uses iframe
method for this clients instead xhr2. 

Hope this helps people in situations as described (php/ZF1 + jquery form plugin).

**Comment by ar-dia** [comment]
Just a side-note, I tested the above-mentioned suggestion, and it results in filename="" on Chrome and filename="blob" on Firefox; however, it does not work for IE11.
Using Blob
```
    var emptyBlob = new Blob([], {type: "application/octet-stream"});
    a.push({name: n, value: emptyBlob, type: el.type});
```
instead of
```
    a.push({ name: n, value: '', type: el.type });
```
as suggested in https://github.com/malsup/form/issues/180 works for Chrome, Firefox and IE11, but results in filename="blob" for all three browsers.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
