### ISSUE TITLE
Post redirect problem

### ISSUE THREAD

**Issue by diegomr86** [jquery-form/form#78]
When I post my form and the return of this post is a redirect, the method sucess is not called. I tryed to test to post with $.post() function of jquery and its the same. But trying with $.ajax() function I dont get this problem. Maybe can be the same problem.

**Comment by malsup** [comment]
Test page?

**Comment by mshick** [comment]
I've also started experiencing this. I use a script which makes a POST for a file upload and receives a 302 in response which redirects to a URL on my local server. After about 10 hours debugging (trying every single version of jQuery since 1.3.2 and every release of jQuery.form since 2.40) I narrowed it to the 2.90 release. 

Everything works fine and the redirects complete successfully (200) in 2.87, but when I upgrade to 2.90 the redirects are aborted (Safari web inspector shows Status: (cancelled) ) and the ajax call results in an error. Same results in latest FF and Chrome.

I will try to help debug by setting up a demo page of some sort, if need be. But perhaps this gives some clues?

**Comment by malsup** [comment]
dlegorm86, your issue should be resolved.  

mshick, the new default behavior for file uploads is to use ajax if the browser supports it (via FormData).  That means redirects won't be followed.  You can force the old behavior using option:  "iframe: true"

**Comment by mshick** [comment]
Thanks, that did the trick. Could have sworn I tried it...

What's the rationale for not following redirects? Isn't that an expected behavior for AJAX?
